### ISSUE TITLE
Highlight the current tree

### ISSUE THREAD

**Issue by bjarnef** [warrenbuckley/Analytics#29]
I think it would be great to highlight the current tree node :)

https://our.umbraco.org/forum/developers/extending-umbraco/63267-Custom-section-mark-currentNode-blue?p=0#comment213103

**Comment by warrenbuckley** [comment]
@bjarnef if you do a pull request for this. I can't remember what me you & @abjerner got stuck on, as I thought we was close to a release? Do you remember?

**Comment by abjerner** [comment]
At least for my part, we had some problems with the WebForms dialog due to the authentication bug in 7.2.2. I was pretty sure I added some code to handle that, but can't find it in the list of commits. I will look into whether I just forgot to commit or whatever I have been doing.

Anyways, according to Our, 7.2.3 is out tomorrow, so we might as well wait to see that everything works for that release.

**Comment by warrenbuckley** [comment]
Yes makes sense to @abjerner to do a release to check it works with 7.2.1, 7.2.2 & 7.2.3

**Comment by abjerner** [comment]
Oh well. Just needed to look in the developer branch: https://github.com/warrenbuckley/Analytics/commit/9cbec98a2f172b2dbf49fc3e838d7ad287e1ee9e

**Comment by bjarnef** [comment]
@warrenbuckley I can take a look at it tonight maybe or some of the next days..

as @abjerner mention there is the bug about UmbracoEnsuredPage in 7.2.2 .. so I think it will be great to wait for 7.2.3 to test in that version too and if the workaround https://github.com/warrenbuckley/Analytics/commit/9cbec98a2f172b2dbf49fc3e838d7ad287e1ee9e fix the issue for 7.2.2

then there is the **$digest** error https://github.com/warrenbuckley/Analytics/issues/28  .. but I am not sure if it breaks anything?

**Comment by warrenbuckley** [comment]
OK so if we can get these couple of things sorted perhaps this week or next then we could have a release (btw on holiday next week, so you guys may need to release it)
