### ISSUE TITLE
Installed Package - Does not show up on tree

### ISSUE THREAD

**Issue by KirschnerMatt** [warrenbuckley/Analytics#47]
Just tried to re-install this on Umbraco 7.4.3 and the link never showed up on my tree. I also checked my user account to see if I needed to enable it and I still couldn't find Analytics there.

What do I have to add to make this show up in the backoffice tree?

**Comment by abjerner** [comment]
If you _Users_ section and select your user, do you see _Analytics_ in the list of checkboxes? It isn't checked by default, so you have to do that manually.

![image](https://cloud.githubusercontent.com/assets/3634580/14568097/b1645e64-0337-11e6-9e76-e38f83058513.png)

If you don't see the checkbox, have you tried rebuilding or restarting your site, and then reloading your browser window? How did you install you site? Via NuGet or as an Umbraco Package? I just tried to install a fresh Umbraco 7.4.3 using NuGet, and it worked fine.

**Comment by KirschnerMatt** [comment]
The issues I'm having are on my dev environment in localhost. I'm aware that the checkbox should show up in Users but I still don't have the option, even after clearing my cache and incrementing the version number in clientDependency.config.

It's worth noting that I used to have the package. In order to update, I uninstalled and then redownloaded/reinstalled the latest version.

Where is the script located that adds the Analytics option in Users? I'd like to check it out to see if the install is editing the proper files.

**Comment by abjerner** [comment]
Okay. So when initially installing the package, it will add `<add key="AnalyticsStartupInstalled" value="True" />` to `appSettings` in your `Web.config`. Is this key present?

From what I can tell, this key isn't removed when uninstalling the package (at least not if you have installed via NuGet), so when you install it again, the package will think it has already been installed, and not add the proper configuration.

So if you remove the key, the package should try to install it self again ;)

Alternatively you can check whether `<add initialize="true" sortOrder="0" alias="analyticsTree" application="analytics" title="Analytics" iconClosed="icon-folder" iconOpen="icon-folder-open" type="Analytics.Controllers.AnalyticsTreeController, Analytics" />` is present in the `~/config/trees.config`, since this is really what will make the it show up in the tree (and the checkbox being shown).

**Comment by KirschnerMatt** [comment]
Okay, removing the AnalyticsStartupInstalled key, then re-installing the package worked.

Thanks!
